Fix CS0053 errors
* Changes values that would cause build error CS0053 to be public instead of their original values; This is probably very wrong but it makes things build so I'm going with it for now
* Fixes JsonPropertyOrder in PmdTarget_Message and PmdTarget_Script
* Remove Data from PmdTarget_Script